sensor_kit_base_link:
  camera0/camera_link:
    x: -0.2474
    y: 0.0
    z: 0.507
    roll: 0.0
    pitch: 0.0
    yaw: 3.14
  camera1/camera_link:
    x: 0.2006
    y: -0.338
    z: 0.507
    roll: 0.0
    pitch: 0.0
    yaw: -1.57
  camera2/camera_link:
    x: 0.2006
    y: 0.338
    z: 0.507
    roll: 0.0
    pitch: 0.0
    yaw: 1.57
  camera3/camera_link:
    x: 0.6546
    y: 0.0
    z: 0.507
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: 0.643
    y: 0.0
    z: 0.192
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.643
    y: 0.0
    z: 0.192
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
